services:
  dnshe-ddns-go-callback:
    image: qrst1ks4/dnshe-ddns-go-callback:latest
    platform: linux/arm64
    container_name: dnshe-ddns-go-callback
    restart: unless-stopped
    ports:
      - "18491:18491"
    volumes:
      - ./data:/data
    environment:
      - PORT=18491
